### ISSUE TITLE
practicas

### ISSUE THREAD

**Issue by grupohernandezalba** [CabreraGerardo/SistemasGeoreferenciados#2]
Excelente @CabreraGerardo muy buen trabajo , me gusto la funcionalidad y el diseño.

![Captura de Pantalla 2020-03-01 a la(s) 12 00 43](https://user-images.githubusercontent.com/14998558/75630974-7d246700-5bb4-11ea-8960-72840f99b329.png)

**Comment by CabreraGerardo** [comment]
Gracias profe

**Comment by grupohernandezalba** [comment]
De nada.
