### ISSUE TITLE
Firebase

### ISSUE THREAD

**Issue by grupohernandezalba** [CabreraGerardo/SistemasGeoreferenciados#3]
Muy bien @CabreraGerardo en los botones de agregar trata de no usar un color rojo ya que casi siempre los usuarios lo asocian con el borrado.

![Captura de Pantalla 2020-03-12 a la(s) 21 24 39](https://user-images.githubusercontent.com/14998558/76586967-0cc8f000-64a8-11ea-8a4d-755ac90e069d.png)

**Comment by CabreraGerardo** [comment]
En seguida lo corrijo, gracias profe
